algoritmo "SOMA"
// Função : somar quatro variaveis inteiras
// Autor : victor hugo
// Data : 23/09/2019
// Seção de Declarações 
var

n1, n2, n3, n4, soma : inteiro

inicio
// Seção de Comandos

escreva("Digite um numero:")
leia(n1)
escreva("Digite um numero:")
leia(n2)
escreva("Digite um numero:")
leia(n3)
escreva("Digite um numero:")
leia(n4)

soma <- n1 + n2 + n3 + n4

escreva("A soma é: ",soma)

fimalgoritmo
